### ISSUE TITLE
Files not loading

### ISSUE THREAD

**Issue by msslava** [iluminar/goodwork#747] opened 2019-10-25 07:33 UTC
### Description:
![error4](https://user-images.githubusercontent.com/3504940/67552059-e978f080-f712-11e9-90d3-2ad014c77486.jpg)
![error3](https://user-images.githubusercontent.com/3504940/67552060-e978f080-f712-11e9-9c7a-86b41f1ea56f.jpg)

**Comment by Hasnayeen** [comment] 2019-10-26 10:02
fixed by edf5c5c, check if the issue is solved

**Closed** 2019-10-26 10:01 UTC

**Comment by msslava** [comment] 2019-10-26 10:46
It is doesn't work. I get new error
![error](https://user-images.githubusercontent.com/3504940/67618354-fd961e00-f7f6-11e9-9574-b7dbcb9f3ea7.png)

**Comment by msslava** [comment] 2019-10-26 10:49
If I upload files through the Files menu - also an error

**Comment by Hasnayeen** [comment] 2019-10-26 12:14
are you trying this in local or in the demo site?

**Comment by msslava** [comment] 2019-10-26 13:20
on my demo site

**Comment by Hasnayeen** [comment] 2019-10-26 13:31
so not on the https://goodworkfor.life/ site? can you describe how to reproduce this? I can't reproduce this on my local or the demo site

**Comment by msslava** [comment] 2019-10-26 13:40
no, on my demo site. You can use my demosite and login as guest, if you want.
http://91.77.162.158/

**Comment by Hasnayeen** [comment] 2019-10-26 13:45
do you have the latest code?

**Comment by Hasnayeen** [comment] 2019-10-26 13:47
can you try clearing route cache to see if its solves the problem

**Comment by Hasnayeen** [comment] 2019-10-26 14:03
also you've to run new migration for file uploading to work in file tab

**Comment by msslava** [comment] 2019-10-26 19:11
Now it's work, thanks

**Comment by msslava** [comment] 2019-10-26 19:44
**But** 
If you reopen the post for editing, then the files are not loaded
